import CapabilityRow from "./CapabilityRow";

const CapabilitiesTable = (props) => {
  return (
    <div className="character_box">
      <CapabilityRow
        topLeft={true}
        bottomRight={false}
        col1="Administer"
        col2="Pilot"
        col3="Work"
        register={props.register}
      />
      <CapabilityRow
        topLeft={false}
        bottomRight={false}
        col1="Connect"
        col2="Program"
        col3="Biosionics"
        register={props.register}
      />
      <CapabilityRow
        topLeft={false}
        bottomRight={false}
        col1="Exert"
        col2="Punch"
        col3="Metapsionics"
        register={props.register}
      />
      <CapabilityRow
        topLeft={false}
        bottomRight={false}
        col1="Fix"
        col2="Shoot"
        col3="Precognition"
        register={props.register}
      />
      <CapabilityRow
        topLeft={false}
        bottomRight={false}
        col1="Heal"
        col2="Sneak"
        col3="Telekinesis"
        register={props.register}
      />
      <CapabilityRow
        topLeft={false}
        bottomRight={false}
        col1="Know"
        col2="Stab"
        col3="Telepathy"
        register={props.register}
      />
      <CapabilityRow
        topLeft={false}
        bottomRight={false}
        col1="Lead"
        col2="Survive"
        col3="Teleportation"
        register={props.register}
      />
      <CapabilityRow
        topLeft={false}
        bottomRight={false}
        col1="Notice"
        col2="Talk"
        col3="-"
        register={props.register}
      />
      <CapabilityRow
        topLeft={false}
        bottomRight={true}
        col1="Perform"
        col2="Trade"
        col3="-"
        register={props.register}
      />
    </div>
  );
};

export default CapabilitiesTable;
